// Generates ports/ios/ThinkingOrbsKit/Sources/ThinkingOrbsKit/OrbSpec.swift
// from spec/orbs-spec.json.
//
// The Swift port hand-transcribes the MATH (that is what the golden tests
// guard), but never the TUNINGS. Those are generated, so a retune in the
// inkform mini page flows to iOS with `npm run spec && npm run codegen:swift`
// instead of someone retyping forty float literals.
//
// Run: npx tsx scripts/codegen-swift.ts

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const spec = JSON.parse(readFileSync(resolve(root, 'spec/orbs-spec.json'), 'utf8'));

const num = (n: number) => (Number.isInteger(n) ? `${n}` : `${n}`);
const optsLiteral = (o: Record<string, number>) =>
  `[${Object.entries(o)
    .map(([k, v]) => `"${k}": ${num(v)}`)
    .join(', ')}]`;

const states = spec.enums.states as string[];
const modes = spec.enums.modes as string[];

const swiftCase = (s: string) => s;

const out = `// GENERATED by scripts/codegen-swift.ts from spec/orbs-spec.json — do not edit.
// spec ${spec.specVersion} · thinking-orbs ${spec.sourceLibrary.version}

import Foundation

/// Which animation to show.
public enum OrbState: String, CaseIterable, Sendable {
${states.map((s) => `    case ${swiftCase(s)} = "${s}"`).join('\n')}

    /// Accessibility label, matching the web component's aria-label.
    public var label: String {
        switch self {
${states.map((s) => `        case .${swiftCase(s)}: return "${spec.labels[s]}"`).join('\n')}
        }
    }

    var mode: OrbMode {
        switch self {
${states.map((s) => `        case .${swiftCase(s)}: return .${spec.stateToMode[s]}`).join('\n')}
        }
    }
}

/// Rendered size in points. Exactly two tuned presets ship — they are
/// separate designs, each with its own dot count and speed, not a scale factor.
public enum OrbSize: Int, CaseIterable, Sendable {
    case px64 = 64
    case px20 = 20

    var value: Double { Double(rawValue) }
}

enum OrbMode: String, CaseIterable, Sendable {
${modes.map((m) => `    case ${m}`).join('\n')}
}

enum OrbSpec {
    /// Per-mode density/geometry before any preset multiplier.
    static let baseProfiles: [OrbMode: [String: Double]] = [
${modes
  .map((m) => `        .${m}: ${optsLiteral(spec.baseProfiles[m])}`)
  .join(',\n')}
    ]

    struct Preset { let speed: Double; let count: Double; let size: Double; let extra: [String: Double] }

    /// Per (mode × size) baked tuning.
    static let presets: [OrbMode: [OrbSize: Preset]] = [
${modes
  .map((m) => {
    const rows = (['64', '20'] as const)
      .map((sz) => {
        const p = spec.presets[m][sz];
        return `            .px${sz}: Preset(speed: ${num(p.speed)}, count: ${num(p.count)}, size: ${num(p.size)}, extra: ${p.extra ? optsLiteral(p.extra) : '[:]'})`;
      })
      .join(',\n');
    return `        .${m}: [\n${rows}\n        ]`;
  })
  .join(',\n')}
    ]

    /// 2-D lattices scale by √count on each axis so the TOTAL scales by count.
    static let countPairs: [(String, String)] = [
${spec.scaling.countPairs.map(([a, b]: [string, string]) => `        ("${a}", "${b}")`).join(',\n')}
    ]
    static let countKeys: [String] = [${spec.scaling.countKeys.map((k: string) => `"${k}"`).join(', ')}]
    static let iconDensityKeys: [String] = [${spec.scaling.iconDensityKeys.map((k: string) => `"${k}"`).join(', ')}]
    static let radiusKeys: [String] = [${spec.scaling.radiusKeys.map((k: string) => `"${k}"`).join(', ')}]

    /// The static frame reduced-motion users see.
    static let reducedMotionT: Double = 0.6
}
`;

const dest = resolve(root, 'ports/ios/ThinkingOrbsKit/Sources/ThinkingOrbsKit/OrbSpec.swift');
writeFileSync(dest, out);
console.log(`OrbSpec.swift — ${states.length} states, ${modes.length} modes (spec ${spec.specVersion})`);
